### ISSUE TITLE
Error: Unknown variable dynamic import: ./layouts/default/index.vue

### ISSUE THREAD

**Issue by DHBin** [DHBin/isme-java-serve#1]
更新前端版本后，点击“基础功能 -> 图标Icon”出现Error: Unknown variable dynamic import: ./layouts/default/index.vue异常

**Comment by DHBin** [comment]
@zclzone 

从admin.isme.top的接口看layout从default变成了空字符串，但是数据库文件没有更新，是做过这个变更吗？
```json
  {
      "id": 14,
      "name": "图标 Icon",
      "code": "Icon",
      "type": "MENU",
      "parentId": 9,
      "path": "/base/icon",
      "redirect": null,
      "icon": "i-fe:feather",
      "component": "/src/views/base/unocss-icon.vue",
      "layout": "",
      "keepAlive": null,
      "method": null,
      "description": null,
      "show": true,
      "enable": true,
      "order": 0
  }
```

**Comment by zclzone** [comment]
> @zclzone
> 
> 从admin.isme.top的接口看layout从default变成了空字符串，但是数据库文件没有更新，是做过这个变更吗？
> 
> ```json
>   {
>       "id": 14,
>       "name": "图标 Icon",
>       "code": "Icon",
>       "type": "MENU",
>       "parentId": 9,
>       "path": "/base/icon",
>       "redirect": null,
>       "icon": "i-fe:feather",
>       "component": "/src/views/base/unocss-icon.vue",
>       "layout": "",
>       "keepAlive": null,
>       "method": null,
>       "description": null,
>       "show": true,
>       "enable": true,
>       "order": 0
>   }
> ```

为了处理多layout切换，layout default已经修改为 null，表示跟随系统，初始化数据库脚本已经同步更新，也可以在资源管理功能修改layout

**Comment by DHBin** [comment]
> > @zclzone
> > 从admin.isme.top的接口看layout从default变成了空字符串，但是数据库文件没有更新，是做过这个变更吗？
> > ```json
> >   {
> >       "id": 14,
> >       "name": "图标 Icon",
> >       "code": "Icon",
> >       "type": "MENU",
> >       "parentId": 9,
> >       "path": "/base/icon",
> >       "redirect": null,
> >       "icon": "i-fe:feather",
> >       "component": "/src/views/base/unocss-icon.vue",
> >       "layout": "",
> >       "keepAlive": null,
> >       "method": null,
> >       "description": null,
> >       "show": true,
> >       "enable": true,
> >       "order": 0
> >   }
> > ```
> 
> 为了处理多layout切换，layout default已经修改为 null，表示跟随系统，初始化数据库脚本已经同步更新，也可以在资源管理功能修改layout

初始化数据库脚本是这个文件吗，我看还是`default`呢
https://github.com/zclzone/isme-nest-serve/blob/main/init.sql#L54

```sql
INSERT INTO `permission` VALUES (14, '图标 Icon', 'Icon', 'MENU', 9, '/base/icon', NULL, 'i-fe:feather', '/src/views/base/unocss-icon.vue', 'default', NULL, NULL, NULL, 1, 1, 0);
```

**Comment by zclzone** [comment]
> > > @zclzone
> > > 从admin.isme.top的接口看layout从default变成了空字符串，但是数据库文件没有更新，是做过这个变更吗？
> > > ```json
> > >   {
> > >       "id": 14,
> > >       "name": "图标 Icon",
> > >       "code": "Icon",
> > >       "type": "MENU",
> > >       "parentId": 9,
> > >       "path": "/base/icon",
> > >       "redirect": null,
> > >       "icon": "i-fe:feather",
> > >       "component": "/src/views/base/unocss-icon.vue",
> > >       "layout": "",
> > >       "keepAlive": null,
> > >       "method": null,
> > >       "description": null,
> > >       "show": true,
> > >       "enable": true,
> > >       "order": 0
> > >   }
> > > ```
> > 
> > 
> > 为了处理多layout切换，layout default已经修改为 null，表示跟随系统，初始化数据库脚本已经同步更新，也可以在资源管理功能修改layout
> 
> 初始化数据库脚本是这个文件吗，我看还是`default`呢 https://github.com/zclzone/isme-nest-serve/blob/main/init.sql#L54
> 
> ```sql
> INSERT INTO `permission` VALUES (14, '图标 Icon', 'Icon', 'MENU', 9, '/base/icon', NULL, 'i-fe:feather', '/src/views/base/unocss-icon.vue', 'default', NULL, NULL, NULL, 1, 1, 0);
> ```

晕，没改全，我再推一次

**Comment by zclzone** [comment]
> > > > @zclzone
> > > > 从admin.isme.top的接口看layout从default变成了空字符串，但是数据库文件没有更新，是做过这个变更吗？
> > > > ```json
> > > >   {
> > > >       "id": 14,
> > > >       "name": "图标 Icon",
> > > >       "code": "Icon",
> > > >       "type": "MENU",
> > > >       "parentId": 9,
> > > >       "path": "/base/icon",
> > > >       "redirect": null,
> > > >       "icon": "i-fe:feather",
> > > >       "component": "/src/views/base/unocss-icon.vue",
> > > >       "layout": "",
> > > >       "keepAlive": null,
> > > >       "method": null,
> > > >       "description": null,
> > > >       "show": true,
> > > >       "enable": true,
> > > >       "order": 0
> > > >   }
> > > > ```
> > > 
> > > 
> > > 为了处理多layout切换，layout default已经修改为 null，表示跟随系统，初始化数据库脚本已经同步更新，也可以在资源管理功能修改layout
> > 
> > 
> > 初始化数据库脚本是这个文件吗，我看还是`default`呢 https://github.com/zclzone/isme-nest-serve/blob/main/init.sql#L54
> > ```sql
> > INSERT INTO `permission` VALUES (14, '图标 Icon', 'Icon', 'MENU', 9, '/base/icon', NULL, 'i-fe:feather', '/src/views/base/unocss-icon.vue', 'default', NULL, NULL, NULL, 1, 1, 0);
> > ```
> 
> 晕，没改全，我再推一次

不是没改全，是改了忘推github了，只推了gitee，现在可以了
